- name: Run database container
  docker_container:
    name: my-database
    image: tomvae/databse:latest
    env:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    state: started
    restart_policy: always
    networks:
      - name: my_network