name: CI devops 2024
on:
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

        - name: Build, test, and analyze with SonarCloud
        run: |
          cd simple-api
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=Tomasvae_devops-livecoding \
            -Dsonar.organization=tomasvae \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
